--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Heisenburger69/BurgerSpawners
build-by-default: true
branches:
- master
projects:
  BurgerSpawners:
    path: ""
    icon: Spawner_JE3.png
...
