name: PHPStan

on: [push, pull_request]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: Create Vendor Directory
      run: |
        echo Making directory...
        mkdir vendor
        echo Directory made.
    - name: wget virions, libFormAPI
      uses: wei/wget@v1
      with:
        args: -O vendor/libFormAPI.phar https://poggit.pmmp.io/r/54590/libFormAPI_dev-2.phar
    - name: Run PHPStan
      uses: nxtlvlsoftware/pmmp-phpstan-action@3
      with:
        phpstan-config: phpstan.neon.dist
